### ISSUE TITLE
run_OF_RGB crashed after TIME (Pyramide+Gradients)

### ISSUE THREAD

**Issue by LaifuLi** [tikroeger/OF_DIS#1]
Hi Till,
I have successfully compiled and generated the 4 targets, but when I try to run the following command
~/Run/OF_DIS-master/build$ ./run_OF_RGB 0000000150.png 0000000151.png out.flo

it printed this and then crashed
TIME (Image loading     ) (ms): 34.086
TIME (Pyramide+Gradients) (ms): 47.42

Can you provide some advice? Thanks a lot!

**Comment by tikroeger** [comment]
Hi!

Can you sent me these two images, or any pther minimal example? I will see
if I can reproduce the error.

You could send them to:
till.kroeger@gmail.com

Thanks!
Till


2017-03-15 23:27 GMT-04:00 LaifuLi <notifications@github.com>:

**Comment by tikroeger** [comment]
Issue could not be reproduced.
