### ISSUE TITLE
how to tune parameters about DIS optialFlow in opencv

### ISSUE THREAD

**Issue by xinguanxi** [tikroeger/OF_DIS#2]
i used DIS optical flow algorithm in OpenCV3.2, and  it is amazingly fast with good quality,but i have a problem about parameters.  with many experiments, i found that parameters may be tuned according to the video. so i was wondering how to tune parameters according the size of video、or something like that 

       
   dis->setFinestScale(3);
	dis->setGradientDescentIterations(8);
	dis->setPatchSize(5);  
	dis->setPatchStride(3);
	dis->setUseMeanNormalization(1);
	dis->setUseSpatialPropagation(1);
	dis->setVariationalRefinementAlpha(10);
	dis->setVariationalRefinementDelta(5);
	dis->setVariationalRefinementGamma(10);
	dis->setVariationalRefinementIterations(12);
```

**Comment by tikroeger** [comment]
The single most important parameter to scale with video size is the coarsest level on the scale pyramid. Each level scales the input size by 1/2. Select the coarsest level such that the maximum expected motion magnitude is captured in the receptive field. For all other parameters please have a look at the paper.

**Comment by reasonW** [comment]
how fast when you use this algorithm in OpenCV 3.2, I find the speed  speed does not reach 300Hz

**Comment by xgxcheer-hit** [comment]
almost 5 fps on 1080P video,but it's fastest algorithm of dense optical flow
